// Contenus de la page d'accueil publique (One Page).
// Structure : fr complet ; les autres langues traduisent les mêmes clés.
export const HOME_CONTENT = {
  fr: {
    nav: { services: "Services", security: "Sécurité", faq: "FAQ", login: "Se connecter", openAccount: "Ouvrir un compte" },
    hero: {
      badge: "Banque en ligne européenne",
      title: "Votre banque, sans compromis.",
      subtitle: "Compte courant, carte de paiement et virements internationaux : gérez votre argent en toute sécurité, où que vous soyez.",
      ctaPrimary: "Ouvrir votre compte",
      ctaSecondary: "Se connecter",
      trust1: "Fonds ségréés",
      trust2: "IBAN européen",
      trust3: "Support multilingue",
      photoAlt: "Un conseiller SCAP BEN accueille deux clients venus ouvrir un compte",
    },
    stats: [
      { value: "27", label: "Pays desservis" },
      { value: "16", label: "Langues disponibles" },
      { value: "50 000+", label: "Clients actifs" },
      { value: "99,9 %", label: "Disponibilité" },
    ],
    services: {
      title: "Des services complets",
      subtitle: "Tout le quotidien d'une banque moderne, dans un espace clair et sécurisé.",
      cards: [
        { title: "Compte courant", desc: "Ouverture simple, IBAN européen et gestion intégrale depuis votre espace." },
        { title: "Cartes de paiement", desc: "Cartes de débit sécurisées, contrôle et blocage instantanés en ligne." },
        { title: "Virements", desc: "Virements SEPA et internationaux avec suivi en temps réel." },
        { title: "Crédits", desc: "Demandes de prêt accompagnées et créditées après signature du contrat." },
        { title: "Relevés PDF", desc: "Historique complet de vos opérations, exportable à tout moment." },
        { title: "Support 7j/7", desc: "Une équipe multilingue joignable par email et par téléphone." },
      ],
    },
    product: {
      title: "Votre argent, sous vos yeux",
      subtitle: "Un tableau de bord clair : solde, graphiques et historique en un coup d'œil.",
      bullets: [
        { title: "Suivi en temps réel", desc: "Chaque opération est visible immédiatement avec sa référence." },
        { title: "Virements en 3 clics", desc: "IBAN, montant, motif : vos virements partent en quelques secondes." },
        { title: "Historique exportable", desc: "Relevés mensuels en PDF, prêts pour vos comptabilités." },
      ],
    },
    cardSection: {
      title: "La carte SCAP BEN",
      subtitle: "Une carte de débit sobre et sécurisée, acceptée partout dans le monde.",
      bullets: [
        "Paiements sans contact et retraits internationaux",
        "Blocage et déblocage instantanés depuis votre espace",
        "Notifications à chaque utilisation",
      ],
    },
    advisor: {
      title: "L'humain reste au centre",
      text: "Derrière l'écran, une vraie équipe : nos conseillers vous accompagnent à l'ouverture de votre compte comme dans vos opérations quotidiennes, dans votre langue.",
    },
    security: {
      title: "La sécurité, notre priorité",
      subtitle: "Des protections concrètes, activées par défaut.",
      items: [
        { title: "Sessions protégées", desc: "Connexion chiffrée et contrôle d'accès strict à votre espace." },
        { title: "Alertes temps réel", desc: "Email et SMS à chaque opération sur votre compte." },
        { title: "Vérification anti-fraude", desc: "Analyse des opérations sensibles avant validation." },
        { title: "Fonds ségréés", desc: "Les fonds des clients sont conservés séparément des fonds de la banque." },
      ],
    },
    faq: {
      title: "Questions fréquentes",
      items: [
        { q: "Comment ouvrir un compte ?", a: "Cliquez sur « Ouvrir un compte », remplissez le formulaire d'inscription et choisissez votre langue. Votre compte est créé immédiatement avec votre IBAN." },
        { q: "Quels documents sont nécessaires ?", a: "Une pièce d'identité en cours de validité et vos coordonnées. Aucun document physique n'est requis pour l'ouverture en ligne." },
        { q: "Combien de temps prend un virement ?", a: "Les virements SEPA sont généralement exécutés sous un jour ouvré. Les virements internationaux dépendent du pays de destination." },
        { q: "Dans quelles langues le service est-il disponible ?", a: "L'interface et les notifications sont disponibles en 16 langues." },
        { q: "Comment contacter un conseiller ?", a: "Écrivez à contact@scap-ben.com ou utilisez votre espace client : notre équipe répond 7 jours sur 7." },
      ],
    },
    cta: { title: "Prêt à rejoindre SCAP BEN ?", subtitle: "Ouvrez votre compte en quelques minutes, depuis n'importe où.", button: "Ouvrir votre compte" },
    footer: {
      legal: "Mentions légales",
      privacy: "Politique de confidentialité",
      terms: "Conditions générales",
      rights: "Tous droits réservés.",
    },
  },

  en: {
    nav: { services: "Services", security: "Security", faq: "FAQ", login: "Log in", openAccount: "Open an account" },
    hero: {
      badge: "European online bank",
      title: "Your bank, without compromise.",
      subtitle: "Current account, payment card and international transfers: manage your money securely, wherever you are.",
      ctaPrimary: "Open your account",
      ctaSecondary: "Log in",
      trust1: "Segregated funds",
      trust2: "European IBAN",
      trust3: "Multilingual support",
      photoAlt: "A SCAP BEN advisor welcomes two clients who have come to open an account",
    },
    stats: [
      { value: "27", label: "Countries served" },
      { value: "16", label: "Languages available" },
      { value: "50,000+", label: "Active clients" },
      { value: "99.9%", label: "Availability" },
    ],
    services: {
      title: "Comprehensive services",
      subtitle: "Everything a modern bank offers, in a clear and secure space.",
      cards: [
        { title: "Current account", desc: "Simple opening, European IBAN and full management from your dashboard." },
        { title: "Payment cards", desc: "Secure debit cards with instant online control and blocking." },
        { title: "Transfers", desc: "SEPA and international transfers with real-time tracking." },
        { title: "Loans", desc: "Assisted loan requests, credited after contract signature." },
        { title: "PDF statements", desc: "Complete transaction history, exportable at any time." },
        { title: "Support 7 days a week", desc: "A multilingual team reachable by email and phone." },
      ],
    },
    product: {
      title: "Your money, at a glance",
      subtitle: "A clear dashboard: balance, charts and history in one look.",
      bullets: [
        { title: "Real-time tracking", desc: "Every transaction is visible immediately with its reference." },
        { title: "Transfers in 3 clicks", desc: "IBAN, amount, label: your transfers are sent in seconds." },
        { title: "Exportable history", desc: "Monthly PDF statements, ready for your accounting." },
      ],
    },
    cardSection: {
      title: "The SCAP BEN card",
      subtitle: "A sober, secure debit card, accepted all over the world.",
      bullets: [
        "Contactless payments and international withdrawals",
        "Instant blocking and unblocking from your dashboard",
        "Notifications on every use",
      ],
    },
    advisor: {
      title: "People stay at the center",
      text: "Behind the screen, a real team: our advisors support you when opening your account as well as in your daily operations, in your language.",
    },
    security: {
      title: "Security is our priority",
      subtitle: "Concrete protections, enabled by default.",
      items: [
        { title: "Protected sessions", desc: "Encrypted connection and strict access control to your account." },
        { title: "Real-time alerts", desc: "Email and SMS for every transaction on your account." },
        { title: "Anti-fraud checks", desc: "Sensitive transactions are analyzed before validation." },
        { title: "Segregated funds", desc: "Client funds are kept separate from the bank's own funds." },
      ],
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        { q: "How do I open an account?", a: "Click on “Open an account”, fill in the registration form and choose your language. Your account is created immediately with your IBAN." },
        { q: "Which documents are required?", a: "A valid ID and your contact details. No physical documents are required for online opening." },
        { q: "How long does a transfer take?", a: "SEPA transfers are usually executed within one business day. International transfers depend on the destination country." },
        { q: "Which languages are available?", a: "The interface and notifications are available in 16 languages." },
        { q: "How do I contact an advisor?", a: "Write to contact@scap-ben.com or use your client area: our team answers 7 days a week." },
      ],
    },
    cta: { title: "Ready to join SCAP BEN?", subtitle: "Open your account in minutes, from anywhere.", button: "Open your account" },
    footer: { legal: "Legal notice", privacy: "Privacy policy", terms: "Terms and conditions", rights: "All rights reserved." },
  },

  de: {
    nav: { services: "Dienstleistungen", security: "Sicherheit", faq: "FAQ", login: "Anmelden", openAccount: "Konto eröffnen" },
    hero: {
      badge: "Europäische Online-Bank",
      title: "Ihre Bank, ohne Kompromisse.",
      subtitle: "Girokonto, Zahlungskarte und internationale Überweisungen: Verwalten Sie Ihr Geld sicher, wo auch immer Sie sind.",
      ctaPrimary: "Konto eröffnen",
      ctaSecondary: "Anmelden",
      trust1: "Getrennt verwahrte Mittel",
      trust2: "Europäische IBAN",
      trust3: "Mehrsprachiger Support",
      photoAlt: "Ein SCAP BEN-Berater begrüßt zwei Kunden, die ein Konto eröffnen möchten",
    },
    stats: [
      { value: "27", label: "Betreute Länder" },
      { value: "16", label: "Verfügbare Sprachen" },
      { value: "50.000+", label: "Aktive Kunden" },
      { value: "99,9 %", label: "Verfügbarkeit" },
    ],
    services: {
      title: "Umfassende Dienstleistungen",
      subtitle: "Alles, was eine moderne Bank bietet, in einem klaren und sicheren Bereich.",
      cards: [
        { title: "Girokonto", desc: "Einfache Eröffnung, europäische IBAN und komplette Verwaltung aus Ihrem Bereich." },
        { title: "Zahlungskarten", desc: "Sichere Debitkarten mit sofortiger Online-Kontrolle und Sperre." },
        { title: "Überweisungen", desc: "SEPA- und internationale Überweisungen mit Echtzeitverfolgung." },
        { title: "Kredite", desc: "Begleitete Kreditanträge, Auszahlung nach Vertragsunterzeichnung." },
        { title: "PDF-Auszüge", desc: "Vollständiger Transaktionsverlauf, jederzeit exportierbar." },
        { title: "Support 7 Tage/Woche", desc: "Ein mehrsprachiges Team per E-Mail und Telefon erreichbar." },
      ],
    },
    product: {
      title: "Ihr Geld, im Blick",
      subtitle: "Ein klares Dashboard: Guthaben, Grafiken und Verlauf auf einen Blick.",
      bullets: [
        { title: "Echtzeitverfolgung", desc: "Jede Transaktion ist sofort mit ihrer Referenz sichtbar." },
        { title: "Überweisungen in 3 Klicks", desc: "IBAN, Betrag, Verwendungszweck: In Sekunden verschickt." },
        { title: "Exportierbarer Verlauf", desc: "Monatliche PDF-Auszüge, bereit für Ihre Buchhaltung." },
      ],
    },
    cardSection: {
      title: "Die SCAP BEN-Karte",
      subtitle: "Eine schlichte, sichere Debitkarte, weltweit akzeptiert.",
      bullets: [
        "Kontaktlose Zahlungen und internationale Abhebungen",
        "Sofortiges Sperren und Entsperren aus Ihrem Bereich",
        "Benachrichtigungen bei jeder Nutzung",
      ],
    },
    advisor: {
      title: "Der Mensch bleibt im Mittelpunkt",
      text: "Hinter dem Bildschirm steht ein echtes Team: Unsere Berater begleiten Sie bei der Kontoeröffnung wie bei Ihren täglichen Vorgängen, in Ihrer Sprache.",
    },
    security: {
      title: "Sicherheit hat Priorität",
      subtitle: "Konkrete Schutzmaßnahmen, standardmäßig aktiv.",
      items: [
        { title: "Geschützte Sitzungen", desc: "Verschlüsselte Verbindung und strenge Zugangskontrolle." },
        { title: "Echtzeit-Warnungen", desc: "E-Mail und SMS bei jeder Transaktion auf Ihrem Konto." },
        { title: "Betrugskontrolle", desc: "Sensible Transaktionen werden vor der Validierung geprüft." },
        { title: "Getrennte Mittel", desc: "Kundengelder werden getrennt von den Bankmitteln verwahrt." },
      ],
    },
    faq: {
      title: "Häufige Fragen",
      items: [
        { q: "Wie eröffne ich ein Konto?", a: "Klicken Sie auf „Konto eröffnen“, füllen Sie das Anmeldeformular aus und wählen Sie Ihre Sprache. Ihr Konto wird sofort mit Ihrer IBAN erstellt." },
        { q: "Welche Unterlagen sind nötig?", a: "Ein gültiger Ausweis und Ihre Kontaktdaten. Für die Online-Eröffnung sind keine physischen Dokumente erforderlich." },
        { q: "Wie lange dauert eine Überweisung?", a: "SEPA-Überweisungen werden in der Regel innerhalb eines Werktags ausgeführt. Internationale Überweisungen hängen vom Zielland ab." },
        { q: "In welchen Sprachen ist der Service verfügbar?", a: "Die Oberfläche und die Benachrichtigungen sind in 16 Sprachen verfügbar." },
        { q: "Wie erreiche ich einen Berater?", a: "Schreiben Sie an contact@scap-ben.com oder nutzen Sie Ihren Kundenbereich: Unser Team antwortet 7 Tage pro Woche." },
      ],
    },
    cta: { title: "Bereit für SCAP BEN?", subtitle: "Eröffnen Sie Ihr Konto in wenigen Minuten, von überall.", button: "Konto eröffnen" },
    footer: { legal: "Impressum", privacy: "Datenschutz", terms: "Allgemeine Geschäftsbedingungen", rights: "Alle Rechte vorbehalten." },
  },

  sk: {
    nav: { services: "Služby", security: "Zabezpečenie", faq: "FAQ", login: "Prihlásiť sa", openAccount: "Otvoriť účet" },
    hero: {
      badge: "Európska internetová banka",
      title: "Vaša banka bez kompromisov.",
      subtitle: "Bežný účet, platobná karta a medzinárodné prevody: spravujte svoje peniaze bezpečne, kdekoľvek ste.",
      ctaPrimary: "Otvoriť účet",
      ctaSecondary: "Prihlásiť sa",
      trust1: "Oddelené prostriedky",
      trust2: "Európska IBAN",
      trust3: "Viacjazyčná podpora",
      photoAlt: "Poradca SCAP BEN víta dvoch klientov, ktorí prídu otvoriť účet",
    },
    stats: [
      { value: "27", label: "Obsluhovaných krajín" },
      { value: "16", label: "Dostupných jazykov" },
      { value: "50 000+", label: "Aktívnych klientov" },
      { value: "99,9 %", label: "Dostupnosť" },
    ],
    services: {
      title: "Kompletné služby",
      subtitle: "Všetko, čo ponúka moderná banka, v prehľadnom a bezpečnom priestore.",
      cards: [
        { title: "Bežný účet", desc: "Jednoduché otvorenie, európska IBAN a úplná správa z vášho priestoru." },
        { title: "Platobné karty", desc: "Bezpečné debetné karty s okamžitým ovládaním a blokovaním online." },
        { title: "Prevody", desc: "SEPA a medzinárodné prevody so sledovaním v reálnom čase." },
        { title: "Úvery", desc: "Sprevádzané žiadosti o pôžičky, pripísané po podpise zmluvy." },
        { title: "Výpisy PDF", desc: "Úplná história operácií, ktorú kedykoľvek vyexportujete." },
        { title: "Podpora 7 dní v týždni", desc: "Viacjazyčný tím dostupný e-mailom a telefónom." },
      ],
    },
    product: {
      title: "Vaše peniaze na prvý pohľad",
      subtitle: "Prehľadný dashboard: zostatok, grafy a história na jeden pohľad.",
      bullets: [
        { title: "Sledovanie v reálnom čase", desc: "Každá operácia je okamžite viditeľná so svojou referenciou." },
        { title: "Prevody na 3 kliknutia", desc: "IBAN, suma, poznámka: prevody odchádzajú v pár sekundách." },
        { title: "Exportovateľná história", desc: "Mesačné výpisy v PDF, pripravené pre vaše účtovníctvo." },
      ],
    },
    cardSection: {
      title: "Karta SCAP BEN",
      subtitle: "Strojová, bezpečná debetná karta prijímaná po celom svete.",
      bullets: [
        "Bezkontaktné platby a medzinárodné výbery",
        "Okamžité zablokovanie a odblokovanie z vášho priestoru",
        "Upozornenia pri každom použití",
      ],
    },
    advisor: {
      title: "Človek ostáva v strede",
      text: "Za obrazovkou stojí skutočný tím: naši poradcovia vás sprevádzajú pri otvorení účtu aj pri každodenných operáciách, vo vašom jazyku.",
    },
    security: {
      title: "Zabezpečenie je našou prioritou",
      subtitle: "Konkrétne ochrany, aktívne v predvolenom nastavení.",
      items: [
        { title: "Chránené relácie", desc: "Šifrované pripojenie a prísna kontrola prístupu do vášho priestoru." },
        { title: "Upozornenia v reálnom čase", desc: "E-mail a SMS pri každej operácii na vašom účte." },
        { title: "Kontrola proti podvodom", desc: "Citlivé operácie sa pred schválením analyzujú." },
        { title: "Oddelené prostriedky", desc: "Prostriedky klientov sú uložené oddelene od prostriedkov banky." },
      ],
    },
    faq: {
      title: "Časté otázky",
      items: [
        { q: "Ako si otvorím účet?", a: "Kliknite na „Otvoriť účet“, vyplňte registračný formulár a vyberte si jazyk. Váš účet sa vytvorí okamžite s vašou IBAN." },
        { q: "Aké dokumenty sú potrebné?", a: "Platný doklad totožnosti a vaše kontaktné údaje. Na online otvorenie nie sú potrebné žiadne fyzické dokumenty." },
        { q: "Ako dlho trvá prevod?", a: "SEPA prevody sa zvyčajne uskutočnia do jedného pracovného dňa. Medzinárodné prevody závisia od krajiny určenia." },
        { q: "V akých jazykoch je služba dostupná?", a: "Rozhranie a upozornenia sú dostupné v 16 jazykoch." },
        { q: "Ako kontaktujem poradcu?", a: "Napíšte na contact@scap-ben.com alebo využite klientsku zónu: náš tím odpovedá 7 dní v týždni." },
      ],
    },
    cta: { title: "Pripravení pripojiť sa k SCAP BEN?", subtitle: "Otvorte si účet za pár minút, odkiaľkoľvek.", button: "Otvoriť účet" },
    footer: { legal: "Právne informácie", privacy: "Zásady ochrany súkromia", terms: "Všeobecné podmienky", rights: "Všetky práva vyhradené." },
  },
  nl: {
    nav: { services: "Diensten", security: "Beveiliging", faq: "FAQ", login: "Inloggen", openAccount: "Account openen" },
    hero: {
      badge: "Europese internetbank",
      title: "Uw bank, zonder compromissen.",
      subtitle: "Lopende rekening, betaalkaart en internationale overschrijvingen: beheer uw geld veilig, waar u ook bent.",
      ctaPrimary: "Account openen",
      ctaSecondary: "Inloggen",
      trust1: "Gescheiden fondsen",
      trust2: "Europese IBAN",
      trust3: "Meertalige ondersteuning",
      photoAlt: "Een SCAP BEN-adviseur verwelkomt twee klanten die een account komen openen",
    },
    stats: [
      { value: "27", label: "Bediende landen" },
      { value: "16", label: "Beschikbare talen" },
      { value: "50.000+", label: "Actieve klanten" },
      { value: "99,9 %", label: "Beschikbaarheid" },
    ],
    services: {
      title: "Volledige dienstverlening",
      subtitle: "Alles wat een moderne bank biedt, in een heldere en veilige omgeving.",
      cards: [
        { title: "Lopende rekening", desc: "Eenvoudig openen, Europese IBAN en volledig beheer vanuit uw omgeving." },
        { title: "Betaalkaarten", desc: "Veilige debetkaarten met directe online controle en blokkering." },
        { title: "Overschrijvingen", desc: "SEPA- en internationale overschrijvingen met realtime opvolging." },
        { title: "Kredieten", desc: "Begeleide kredietaanvragen, bijgeschreven na ondertekening van het contract." },
        { title: "PDF-overzichten", desc: "Volledige transactiehistorie, op elk moment exporteerbaar." },
        { title: "Ondersteuning 7 dagen/week", desc: "Een meertalig team bereikbaar per e-mail en telefoon." },
      ],
    },
    product: {
      title: "Uw geld, in één oogopslag",
      subtitle: "Een helder dashboard: saldo, grafieken en historie in één blik.",
      bullets: [
        { title: "Realtime opvolging", desc: "Elke transactie is direct zichtbaar met zijn referentie." },
        { title: "Overschrijvingen in 3 klikken", desc: "IBAN, bedrag, mededeling: uw overschrijvingen vertrekken in enkele seconden." },
        { title: "Exporteerbare historie", desc: "Maandelijkse PDF-overzichten, klaar voor uw boekhouding." },
      ],
    },
    cardSection: {
      title: "De SCAP BEN-kaart",
      subtitle: "Een sobere, veilige debetkaart, wereldwijd geaccepteerd.",
      bullets: [
        "Contactloze betalingen en internationale opnames",
        "Onmiddellijk blokkeren en deblokkeren vanuit uw omgeving",
        "Meldingen bij elk gebruik",
      ],
    },
    advisor: {
      title: "De mens blijft centraal",
      text: "Achter het scherm staat een echt team: onze adviseurs begeleiden u bij het openen van uw account net als bij uw dagelijkse verrichtingen, in uw taal.",
    },
    security: {
      title: "Veiligheid is onze prioriteit",
      subtitle: "Concrete beschermingen, standaard actief.",
      items: [
        { title: "Beveiligde sessies", desc: "Versleutelde verbinding en strikte toegangscontrole tot uw omgeving." },
        { title: "Realtime waarschuwingen", desc: "E-mail en SMS bij elke verrichting op uw rekening." },
        { title: "Fraudecontrole", desc: "Gevoelige transacties worden geanalyseerd vóór validatie." },
        { title: "Gescheiden fondsen", desc: "Klantengelden worden apart bewaard van de gelden van de bank." },
      ],
    },
    faq: {
      title: "Veelgestelde vragen",
      items: [
        { q: "Hoe open ik een account?", a: "Klik op „Account openen“, vul het registratieformulier in en kies uw taal. Uw account wordt onmiddellijk aangemaakt met uw IBAN." },
        { q: "Welke documenten zijn nodig?", a: "Een geldig identiteitsbewijs en uw contactgegevens. Voor het online openen zijn geen fysieke documenten nodig." },
        { q: "Hoe lang duurt een overschrijving?", a: "SEPA-overschrijvingen worden doorgaans binnen één werkdag uitgevoerd. Internationale overschrijvingen hangen af van het bestemmingsland." },
        { q: "In welke talen is de dienst beschikbaar?", a: "De interface en de meldingen zijn beschikbaar in 16 talen." },
        { q: "Hoe bereik ik een adviseur?", a: "Schrijf naar contact@scap-ben.com of gebruik uw klantzone: ons team antwoordt 7 dagen per week." },
      ],
    },
    cta: { title: "Klaar om toe te treden tot SCAP BEN?", subtitle: "Open uw account in enkele minuten, van waar dan ook.", button: "Account openen" },
    footer: { legal: "Juridische informatie", privacy: "Privacybeleid", terms: "Algemene voorwaarden", rights: "Alle rechten voorbehouden." },
  },

  fi: {
    nav: { services: "Palvelut", security: "Turvallisuus", faq: "UKK", login: "Kirjaudu", openAccount: "Avaa tili" },
    hero: {
      badge: "Eurooppalainen verkkopankki",
      title: "Pankkisi, ilman kompromisseja.",
      subtitle: "Tili, maksukortti ja kansainväliset siirrot: hallitse rahojasi turvallisesti, missä tahansa olet.",
      ctaPrimary: "Avaa tili",
      ctaSecondary: "Kirjaudu",
      trust1: "Erotetut varat",
      trust2: "Eurooppalainen IBAN",
      trust3: "Monikielinen tuki",
      photoAlt: "SCAP BEN -neuvoja toivottaa kaksi asiakasta tervetulleiksi avaamaan tiliä",
    },
    stats: [
      { value: "27", label: "Palvelumaita" },
      { value: "16", label: "Saatavilla olevat kielet" },
      { value: "50 000+", label: "Aktiivisia asiakkaita" },
      { value: "99,9 %", label: "Saatavuus" },
    ],
    services: {
      title: "Kattavat palvelut",
      subtitle: "Kaikki mitä moderni pankki tarjoaa, selkeässä ja turvallisessa ympäristössä.",
      cards: [
        { title: "Tili", desc: "Yksinkertainen avaaminen, eurooppalainen IBAN ja täysi hallinta omasta tilastasi." },
        { title: "Maksukortit", desc: "Turvalliset debit-kortit välittömällä online-hallinnalla ja estolla." },
        { title: "Siirrot", desc: "SEPA- ja kansainväliset siirrot reaaliaikaisella seurannalla." },
        { title: "Lainat", desc: "Saatetut lainahakemukset, hyvitetään sopimuksen allekirjoituksen jälkeen." },
        { title: "PDF-tiliotteet", desc: "Täysi tapahtumahistoria, ladattavissa milloin tahansa." },
        { title: "Tuki 7 päivää viikossa", desc: "Monikielinen tiimi tavoitettavissa sähköpostitse ja puhelimitse." },
      ],
    },
    product: {
      title: "Rahasi yhdellä silmäyksellä",
      subtitle: "Selkeä hallintapaneeli: saldo, kaaviot ja historia yhdellä silmäyksellä.",
      bullets: [
        { title: "Reaaliaikainen seuranta", desc: "Jokainen tapahtuma näkyy heti viitteineen." },
        { title: "Siirrot 3 klikkauksella", desc: "IBAN, summa, viesti: siirrot lähtevät muutamassa sekunnissa." },
        { title: "Vietävä historia", desc: "Kuukausittaiset PDF-tiliotteet valmiina kirjanpitoasi varten." },
      ],
    },
    cardSection: {
      title: "SCAP BEN -kortti",
      subtitle: "Natiivi, turvallinen debit-kortti, hyväksytään kaikkialla maailmassa.",
      bullets: [
        "Kontaktittomat maksut ja kansainväliset nostot",
        "Välitön esto ja eston poisto omasta tilastasi",
        "Ilmoitukset jokaisesta käytöstä",
      ],
    },
    advisor: {
      title: "Ihminen pysyy keskiössä",
      text: "Ruudun takana on aito tiimi: neuvostamme saattavat sinut tilin avaamisessa sekä päivittäisissä toiminnoissa, omalla kielelläsi.",
    },
    security: {
      title: "Turvallisuus on prioriteettimme",
      subtitle: "Käytännön suojaukset, oletuksena päällä.",
      items: [
        { title: "Suojatut istunnot", desc: "Salattu yhteys ja tiukka pääsynhallinta tiliisi." },
        { title: "Reaaliaikaiset hälytykset", desc: "Sähköposti ja SMS jokaisesta tilisi tapahtumasta." },
        { title: "Petostentarkistus", desc: "Arkaluontoiset tapahtumat analysoidaan ennen hyväksyntää." },
        { title: "Erotetut varat", desc: "Asiakkaiden varat säilytetään erillään pankin omista varoista." },
      ],
    },
    faq: {
      title: "Usein kysytyt kysymykset",
      items: [
        { q: "Miten avaan tilin?", a: "Napsauta ”Avaa tili”, täytä rekisteröintilomake ja valitse kielisi. Tilisi luodaan heti IBAN:ineen." },
        { q: "Mitä asiakirjoja tarvitaan?", a: "Voimassa oleva henkilötodistus ja yhteystietosi. Verkossa avaamiseen ei tarvita paperiasiakirjoja." },
        { q: "Kuinka kauan siirto kestää?", a: "SEPA-siirrot toteutuvat yleensä yhden arkipäivän kuluessa. Kansainväliset siirrot riippuvat kohdemaasta." },
        { q: "Millä kielillä palvelu on saatavilla?", a: "Käyttöliittymä ja ilmoitukset ovat saatavilla 16 kielellä." },
        { q: "Miten tavoitan neuvonantajan?", a: "Kirjoita osoitteeseen contact@scap-ben.com tai käytä asiakasaluetta: tiimimme vastaa 7 päivää viikossa." },
      ],
    },
    cta: { title: "Valmis liittymään SCAP BENiin?", subtitle: "Avaa tilisi muutamassa minuutissa, mistä tahansa.", button: "Avaa tili" },
    footer: { legal: "Juridiset tiedot", privacy: "Tietosuojakäytäntö", terms: "Yleiset ehdot", rights: "Kaikki oikeudet pidätetään." },
  },

  es: {
    nav: { services: "Servicios", security: "Seguridad", faq: "FAQ", login: "Iniciar sesión", openAccount: "Abrir una cuenta" },
    hero: {
      badge: "Banca en línea europea",
      title: "Su banco, sin concesiones.",
      subtitle: "Cuenta corriente, tarjeta de pago y transferencias internacionales: gestione su dinero con seguridad, esté donde esté.",
      ctaPrimary: "Abrir su cuenta",
      ctaSecondary: "Iniciar sesión",
      trust1: "Fondos segregados",
      trust2: "IBAN europeo",
      trust3: "Soporte multilingüe",
      photoAlt: "Un asesor de SCAP BEN da la bienvenida a dos clientes que vienen a abrir una cuenta",
    },
    stats: [
      { value: "27", label: "Países atendidos" },
      { value: "16", label: "Idiomas disponibles" },
      { value: "50 000+", label: "Clientes activos" },
      { value: "99,9 %", label: "Disponibilidad" },
    ],
    services: {
      title: "Servicios completos",
      subtitle: "Todo el día a día de un banco moderno, en un espacio claro y seguro.",
      cards: [
        { title: "Cuenta corriente", desc: "Apertura sencilla, IBAN europeo y gestión integral desde su espacio." },
        { title: "Tarjetas de pago", desc: "Tarjetas de débito seguras, control y bloqueo instantáneos en línea." },
        { title: "Transferencias", desc: "Transferencias SEPA e internacionales con seguimiento en tiempo real." },
        { title: "Créditos", desc: "Solicitudes de préstamo acompañadas y acreditadas tras la firma del contrato." },
        { title: "Extractos PDF", desc: "Historial completo de sus operaciones, exportable en cualquier momento." },
        { title: "Soporte 7 días/7", desc: "Un equipo multilingüe accesible por email y por teléfono." },
      ],
    },
    product: {
      title: "Su dinero, a la vista",
      subtitle: "Un panel claro: saldo, gráficos e historial de un vistazo.",
      bullets: [
        { title: "Seguimiento en tiempo real", desc: "Cada operación es visible de inmediato con su referencia." },
        { title: "Transferencias en 3 clics", desc: "IBAN, importe, concepto: sus transferencias salen en segundos." },
        { title: "Historial exportable", desc: "Extractos mensuales en PDF, listos para su contabilidad." },
      ],
    },
    cardSection: {
      title: "La tarjeta SCAP BEN",
      subtitle: "Una tarjeta de débito sobria y segura, aceptada en todo el mundo.",
      bullets: [
        "Pagos sin contacto y retiradas internacionales",
        "Bloqueo y desbloqueo instantáneos desde su espacio",
        "Notificaciones en cada uso",
      ],
    },
    advisor: {
      title: "La persona sigue en el centro",
      text: "Detrás de la pantalla hay un equipo real: nuestros asesores le acompañan en la apertura de su cuenta y en sus operaciones diarias, en su idioma.",
    },
    security: {
      title: "La seguridad, nuestra prioridad",
      subtitle: "Protecciones concretas, activadas por defecto.",
      items: [
        { title: "Sesiones protegidas", desc: "Conexión cifrada y control de acceso estricto a su espacio." },
        { title: "Alertas en tiempo real", desc: "Email y SMS en cada operación de su cuenta." },
        { title: "Verificación antifraude", desc: "Análisis de las operaciones sensibles antes de validarlas." },
        { title: "Fondos segregados", desc: "Los fondos de los clientes se conservan separados de los fondos del banco." },
      ],
    },
    faq: {
      title: "Preguntas frecuentes",
      items: [
        { q: "¿Cómo abrir una cuenta?", a: "Haga clic en «Abrir una cuenta», rellene el formulario de registro y elija su idioma. Su cuenta se crea de inmediato con su IBAN." },
        { q: "¿Qué documentos son necesarios?", a: "Un documento de identidad en vigor y sus datos de contacto. No se requiere ningún documento físico para la apertura en línea." },
        { q: "¿Cuánto tarda una transferencia?", a: "Las transferencias SEPA se ejecutan generalmente en un día laborable. Las internacionales dependen del país de destino." },
        { q: "¿En qué idiomas está disponible el servicio?", a: "La interfaz y las notificaciones están disponibles en 16 idiomas." },
        { q: "¿Cómo contactar con un asesor?", a: "Escriba a contact@scap-ben.com o utilice su área de cliente: nuestro equipo responde los 7 días de la semana." },
      ],
    },
    cta: { title: "¿Listo para unirse a SCAP BEN?", subtitle: "Abra su cuenta en unos minutos, desde cualquier lugar.", button: "Abrir su cuenta" },
    footer: { legal: "Aviso legal", privacy: "Política de privacidad", terms: "Condiciones generales", rights: "Todos los derechos reservados." },
  },

  pl: {
    nav: { services: "Usługi", security: "Bezpieczeństwo", faq: "FAQ", login: "Zaloguj się", openAccount: "Otwórz konto" },
    hero: {
      badge: "Europejski bank internetowy",
      title: "Twój bank, bez kompromisów.",
      subtitle: "Konto osobiste, karta płatnicza i przelewy międzynarodowe: zarządzaj swoimi pieniędzmi bezpiecznie, gdziekolwiek jesteś.",
      ctaPrimary: "Otwórz konto",
      ctaSecondary: "Zaloguj się",
      trust1: "Oddzielone środki",
      trust2: "Europejski IBAN",
      trust3: "Obsługa w wielu językach",
      photoAlt: "Doradca SCAP BEN wita dwóch klientów, którzy przychodzą otworzyć konto",
    },
    stats: [
      { value: "27", label: "Obsługiwane kraje" },
      { value: "16", label: "Dostępne języki" },
      { value: "50 000+", label: "Aktywni klienci" },
      { value: "99,9 %", label: "Dostępność" },
    ],
    services: {
      title: "Kompleksowe usługi",
      subtitle: "Wszystko, co oferuje nowoczesny bank, w przejrzystej i bezpiecznej przestrzeni.",
      cards: [
        { title: "Konto osobiste", desc: "Proste otwarcie, europejski IBAN i pełna obsługa z Twojej przestrzeni." },
        { title: "Karty płatnicze", desc: "Bezpieczne karty debetowe z natychmiastową kontrolą i blokadą online." },
        { title: "Przelewy", desc: "Przelewy SEPA i międzynarodowe ze śledzeniem w czasie rzeczywistym." },
        { title: "Kredyty", desc: "Wspierane wnioski kredytowe, uznawane po podpisaniu umowy." },
        { title: "Wyciągi PDF", desc: "Pełna historia operacji, eksportowalna w każdej chwili." },
        { title: "Wsparcie 7 dni w tygodniu", desc: "Wielojęzyczny zespół dostępny mailowo i telefonicznie." },
      ],
    },
    product: {
      title: "Twoje pieniądze na wyciągnięcie ręki",
      subtitle: "Przejrzysty panel: saldo, wykresy i historia w jednym spojrzeniu.",
      bullets: [
        { title: "Śledzenie w czasie rzeczywistym", desc: "Każda operacja jest natychmiast widoczna ze swoim odniesieniem." },
        { title: "Przelew w 3 kliknięciach", desc: "IBAN, kwota, tytuł: przelewy wychodzą w kilka sekund." },
        { title: "Historia do eksportu", desc: "Miesięczne wyciągi PDF, gotowe dla Twojej księgowości." },
      ],
    },
    cardSection: {
      title: "Karta SCAP BEN",
      subtitle: "Skromna, bezpieczna karta debetowa akceptowana na całym świecie.",
      bullets: [
        "Płatności zbliżeniowe i międzynarodowe wypłaty",
        "Natychmiastowa blokada i odblokowanie z Twojej przestrzeni",
        "Powiadomienia przy każdym użyciu",
      ],
    },
    advisor: {
      title: "Człowiek pozostaje w centrum",
      text: "Za ekranem stoi prawdziwy zespół: nasi doradcy wspierają Cię przy otwarciu konta jak i w codziennych operacjach, w Twoim języku.",
    },
    security: {
      title: "Bezpieczeństwo naszym priorytetem",
      subtitle: "Konkretne zabezpieczenia, domyślnie włączone.",
      items: [
        { title: "Chronione sesje", desc: "Szyfrowane połączenie i ścisła kontrola dostępu do Twojej przestrzeni." },
        { title: "Alerty w czasie rzeczywistym", desc: "E-mail i SMS przy każdej operacji na Twoim koncie." },
        { title: "Kontrola antyfraudowa", desc: "Analiza wrażliwych operacji przed zatwierdzeniem." },
        { title: "Oddzielone środki", desc: "Środki klientów są przechowywane oddzielnie od środków banku." },
      ],
    },
    faq: {
      title: "Częste pytania",
      items: [
        { q: "Jak otworzyć konto?", a: "Kliknij „Otwórz konto”, wypełnij formularz rejestracyjny i wybierz swój język. Twoje konto zostanie utworzone natychmiast z Twoim IBAN-em." },
        { q: "Jakie dokumenty są potrzebne?", a: "Ważny dokument tożsamości i Twoje dane kontaktowe. Do otwarcia online nie są wymagane żadne dokumenty fizyczne." },
        { q: "Ile trwa przelew?", a: "Przelewy SEPA są zazwyczaj realizowane w ciągu jednego dnia roboczego. Przelewy międzynarodowe zależą od kraju docelowego." },
        { q: "W jakich językach dostępna jest usługa?", a: "Interfejs i powiadomienia są dostępne w 16 językach." },
        { q: "Jak skontaktować się z doradcą?", a: "Napisz na contact@scap-ben.com lub skorzystaj ze strefy klienta: nasz zespół odpowiada 7 dni w tygodniu." },
      ],
    },
    cta: { title: "Gotowy dołączyć do SCAP BEN?", subtitle: "Otwórz konto w kilka minut, z dowolnego miejsca.", button: "Otwórz konto" },
    footer: { legal: "Informacje prawne", privacy: "Polityka prywatności", terms: "Ogólne warunki", rights: "Wszelkie prawa zastrzeżone." },
  },

  pt: {
    nav: { services: "Serviços", security: "Segurança", faq: "FAQ", login: "Entrar", openAccount: "Abrir uma conta" },
    hero: {
      badge: "Banco online europeu",
      title: "O seu banco, sem compromissos.",
      subtitle: "Conta à ordem, cartão de pagamento e transferências internacionais: gerencie o seu dinheiro com segurança, onde quer que esteja.",
      ctaPrimary: "Abrir a sua conta",
      ctaSecondary: "Entrar",
      trust1: "Fundos segregados",
      trust2: "IBAN europeu",
      trust3: "Suporte multilingue",
      photoAlt: "Um conselheiro da SCAP BEN dá as boas-vindas a dois clientes que vêm abrir uma conta",
    },
    stats: [
      { value: "27", label: "Países servidos" },
      { value: "16", label: "Idiomas disponíveis" },
      { value: "50 000+", label: "Clientes ativos" },
      { value: "99,9 %", label: "Disponibilidade" },
    ],
    services: {
      title: "Serviços completos",
      subtitle: "Todo o dia a dia de um banco moderno, num espaço claro e seguro.",
      cards: [
        { title: "Conta à ordem", desc: "Abertura simples, IBAN europeu e gestão integral a partir do seu espaço." },
        { title: "Cartões de pagamento", desc: "Cartões de débito seguros, controlo e bloqueio instantâneos online." },
        { title: "Transferências", desc: "Transferências SEPA e internacionais com acompanhamento em tempo real." },
        { title: "Créditos", desc: "Pedidos de empréstimo acompanhados e creditados após assinatura do contrato." },
        { title: "Extratos PDF", desc: "Histórico completo das suas operações, exportável a qualquer momento." },
        { title: "Suporte 7 dias/7", desc: "Uma equipa multilingue acessível por email e por telefone." },
      ],
    },
    product: {
      title: "O seu dinheiro, sob os seus olhos",
      subtitle: "Um painel claro: saldo, gráficos e histórico num relance.",
      bullets: [
        { title: "Acompanhamento em tempo real", desc: "Cada operação é visível imediatamente com a sua referência." },
        { title: "Transferências em 3 cliques", desc: "IBAN, montante, descrição: as suas transferências partem em segundos." },
        { title: "Histórico exportável", desc: "Extratos mensais em PDF, prontos para a sua contabilidade." },
      ],
    },
    cardSection: {
      title: "O cartão SCAP BEN",
      subtitle: "Um cartão de débito sóbrio e seguro, aceite em todo o mundo.",
      bullets: [
        "Pagamentos sem contacto e levantamentos internacionais",
        "Bloqueio e desbloqueio instantâneos a partir do seu espaço",
        "Notificações a cada utilização",
      ],
    },
    advisor: {
      title: "O humano continua no centro",
      text: "Atrás do ecrã existe uma equipa real: os nossos conselheiros acompanham-na na abertura da sua conta como nas suas operações diárias, no seu idioma.",
    },
    security: {
      title: "A segurança, a nossa prioridade",
      subtitle: "Proteções concretas, ativadas por padrão.",
      items: [
        { title: "Sessões protegidas", desc: "Ligação encriptada e controlo de acesso rigoroso ao seu espaço." },
        { title: "Alertas em tempo real", desc: "Email e SMS a cada operação na sua conta." },
        { title: "Verificação antifraude", desc: "Análise das operações sensíveis antes da validação." },
        { title: "Fundos segregados", desc: "Os fundos dos clientes são conservados separadamente dos fundos do banco." },
      ],
    },
    faq: {
      title: "Perguntas frequentes",
      items: [
        { q: "Como abrir uma conta?", a: "Clique em «Abrir uma conta», preencha o formulário de registo e escolha o seu idioma. A sua conta é criada imediatamente com o seu IBAN." },
        { q: "Quais documentos são necessários?", a: "Um documento de identidade válido e os seus contactos. Nenhum documento físico é exigido para a abertura online." },
        { q: "Quanto tempo demora uma transferência?", a: "As transferências SEPA são geralmente executadas num dia útil. As internacionais dependem do país de destino." },
        { q: "Em que idiomas está disponível o serviço?", a: "A interface e as notificações estão disponíveis em 16 idiomas." },
        { q: "Como contactar um conselheiro?", a: "Escreva para contact@scap-ben.com ou utilize a sua área de cliente: a nossa equipa responde 7 dias por semana." },
      ],
    },
    cta: { title: "Pronto para se juntar à SCAP BEN?", subtitle: "Abra a sua conta em poucos minutos, de qualquer lugar.", button: "Abrir a sua conta" },
    footer: { legal: "Aviso legal", privacy: "Política de privacidade", terms: "Condições gerais", rights: "Todos os direitos reservados." },
  },

  bg: {
    nav: { services: "Услуги", security: "Сигурност", faq: "Въпроси", login: "Вход", openAccount: "Отворете сметка" },
    hero: {
      badge: "Европейска онлайн банка",
      title: "Вашата банка, без компромиси.",
      subtitle: "Разплащателна сметка, платежна карта и международни преводи: управлявайте парите си сигурно, където и да сте.",
      ctaPrimary: "Отворете сметка",
      ctaSecondary: "Вход",
      trust1: "Отделни средства",
      trust2: "Европейски IBAN",
      trust3: "Многоезична поддръжка",
      photoAlt: "Консултант на SCAP BEN посреща двама клиенти, дошли да отворят сметка",
    },
    stats: [
      { value: "27", label: "Обслужвани държави" },
      { value: "16", label: "Налични езици" },
      { value: "50 000+", label: "Активни клиенти" },
      { value: "99,9 %", label: "Наличност" },
    ],
    services: {
      title: "Пълни услуги",
      subtitle: "Всичко от ежедневието на модерна банка, в ясно и сигурно пространство.",
      cards: [
        { title: "Разплащателна сметка", desc: "Лесно откриване, европейски IBAN и пълно управление от вашето пространство." },
        { title: "Платежни карти", desc: "Сигурни дебитни карти с мигновен онлайн контрол и блокиране." },
        { title: "Преводи", desc: "SEPA и международни преводи със проследяване в реално време." },
        { title: "Кредити", desc: "Съпроводени кредитни заявления, внасяни след подписване на договора." },
        { title: "PDF извлечения", desc: "Пълна история на операциите, за експортиране по всяко време." },
        { title: "Поддръжка 7 дни в седмицата", desc: "Многоезичен екип, достъпен по имейл и телефон." },
      ],
    },
    product: {
      title: "Вашите пари, пред очите ви",
      subtitle: "Ясно табло: салдо, графики и история с един поглед.",
      bullets: [
        { title: "Проследяване в реално време", desc: "Всяка операция е видима веднага с референцията си." },
        { title: "Преводи с 3 клика", desc: "IBAN, сума, основание: преводите тръгват за секунди." },
        { title: "История за експорт", desc: "Месечни PDF извлечения, готови за вашето счетоводство." },
      ],
    },
    cardSection: {
      title: "Картата SCAP BEN",
      subtitle: "Сдържана, сигурна дебитна карта, приета по целия свят.",
      bullets: [
        "Контактни плащания и международни тегления",
        "Мигновено блокиране и отключване от вашето пространство",
        "Известия при всяка употреба",
      ],
    },
    advisor: {
      title: "Човекът остава в центъра",
      text: "Зад екрана стои истински екип: нашите консултанти ви съпровождат при откриването на сметката ви както и при ежедневните ви операции, на вашия език.",
    },
    security: {
      title: "Сигурността е наш приоритет",
      subtitle: "Конкретни защити, активирани по подразбиране.",
      items: [
        { title: "Защитени сесии", desc: "Криптирана връзка и строг контрол на достъпа до вашето пространство." },
        { title: "Сигнали в реално време", desc: "Имейл и SMS при всяка операция по сметката ви." },
        { title: "Антифрод проверка", desc: "Анализ на чувствителните операции преди валидиране." },
        { title: "Отделни средства", desc: "Средствата на клиентите се пазят отделно от средствата на банката." },
      ],
    },
    faq: {
      title: "Често задавани въпроси",
      items: [
        { q: "Как да отворя сметка?", a: "Кликнете върху „Отворете сметка“, попълнете формата за регистрация и изберете езика си. Сметката ви се създава веднага с вашия IBAN." },
        { q: "Какви документи са необходими?", a: "Валиден документ за самоличност и вашите данни за контакт. За онлайн откриване не са необходими физически документи." },
        { q: "Колко време отнема един превод?", a: "SEPA преводите обикновено се изпълняват в рамките на един работен ден. Международните зависят от държавата-получател." },
        { q: "На какви езици е достъпна услугата?", a: "Интерфейсът и известията са достъпни на 16 езика." },
        { q: "Как да се свържа с консултант?", a: "Пишете на contact@scap-ben.com или използвайте клиентското си пространство: нашият екип отговаря 7 дни в седмицата." },
      ],
    },
    cta: { title: "Готови ли сте да се присъедините към SCAP BEN?", subtitle: "Отворете сметката си за няколко минути, отвсякъде.", button: "Отворете сметка" },
    footer: { legal: "Правна информация", privacy: "Политика за поверителност", terms: "Общи условия", rights: "Всички права запазени." },
  },

  el: {
    nav: { services: "Υπηρεσίες", security: "Ασφάλεια", faq: "Συχνές ερωτήσεις", login: "Σύνδεση", openAccount: "Άνοιγμα λογαριασμού" },
    hero: {
      badge: "Ευρωπαϊκή διαδικτυακή τράπεζα",
      title: "Η τράπεζά σας, χωρίς συμβιβασμούς.",
      subtitle: "Λογαριασμός, κάρτα πληρωμών και διεθνείς μεταφορές: διαχειριστείτε τα χρήματά σας με ασφάλεια, όπου κι αν βρίσκεστε.",
      ctaPrimary: "Άνοιγμα λογαριασμού",
      ctaSecondary: "Σύνδεση",
      trust1: "Διαχωρισμένα κεφάλαια",
      trust2: "Ευρωπαϊκό IBAN",
      trust3: "Πολύγλωσση υποστήριξη",
      photoAlt: "Ένας σύμβουλος της SCAP BEN υποδέχεται δύο πελάτες που έρχονται να ανοίξουν λογαριασμό",
    },
    stats: [
      { value: "27", label: "Εξυπηρετούμενες χώρες" },
      { value: "16", label: "Διαθέσιμες γλώσσες" },
      { value: "50.000+", label: "Ενεργοί πελάτες" },
      { value: "99,9 %", label: "Διαθεσιμότητα" },
    ],
    services: {
      title: "Ολοκληρωμένες υπηρεσίες",
      subtitle: "Όλη η καθημερινότητα μιας σύγχρονης τράπεζας, σε έναν σαφή και ασφαλή χώρο.",
      cards: [
        { title: "Λογαριασμός", desc: "Απλό άνοιγμα, ευρωπαϊκό IBAN και πλήρης διαχείριση από τον χώρο σας." },
        { title: "Κάρτες πληρωμών", desc: "Ασφαλείς χρεωστικές κάρτες με άμεσο online έλεγχο και μπλοκάρισμα." },
        { title: "Μεταφορές", desc: "Μεταφορές SEPA και διεθνείς με παρακολούθηση σε πραγματικό χρόνο." },
        { title: "Δάνεια", desc: "Συνοδευόμενες αιτήσεις δανείου, πίστωση μετά την υπογραφή της σύμβασης." },
        { title: "Εκτυπώσεις PDF", desc: "Πλήρες ιστορικό συναλλαγών, εξαγώγιμο ανά πάσα στιγμή." },
        { title: "Υποστήριξη 7 ημέρες/εβδομάδα", desc: "Πολύγλωσση ομάδα διαθέσιμη μέσω email και τηλεφώνου." },
      ],
    },
    product: {
      title: "Τα χρήματά σας, μπροστά στα μάτια σας",
      subtitle: "Ένα σαφές ταμπλό: υπόλοιπο, γραφήματα και ιστορικό με μια ματιά.",
      bullets: [
        { title: "Παρακολούθηση σε πραγματικό χρόνο", desc: "Κάθε συναλλαγή είναι ορατή αμέσως με την αναφορά της." },
        { title: "Μεταφορές σε 3 κλικ", desc: "IBAN, ποσό, αιτία: οι μεταφορές σας φεύγουν σε δευτερόλεπτα." },
        { title: "Εξαγώγιμο ιστορικό", desc: "Μηνιαίες εκτυπώσεις PDF, έτοιμες για τη λογιστική σας." },
      ],
    },
    cardSection: {
      title: "Η κάρτα SCAP BEN",
      subtitle: "Μια λιτή, ασφαλής χρεωστική κάρτα, αποδεκτή παντού στον κόσμο.",
      bullets: [
        "Ανέπαφες πληρωμές και διεθνείς αναλήψεις",
        "Άμεσο μπλοκάρισμα και ξεκλείδωμα από τον χώρο σας",
        "Ειδοποιήσεις σε κάθε χρήση",
      ],
    },
    advisor: {
      title: "Ο άνθρωπος παραμένει στο κέντρο",
      text: "Πίσω από την οθόνη υπάρχει μια πραγματική ομάδα: οι σύμβουλοί μας σας συνοδεύουν στο άνοιγμα του λογαριασμού σας καθώς και στις καθημερινές σας συναλλαγές, στη γλώσσα σας.",
    },
    security: {
      title: "Η ασφάλεια, προτεραιότητά μας",
      subtitle: "Συγκεκριμένες προστασίες, ενεργοποιημένες εξ ορισμού.",
      items: [
        { title: "Προστατευμένες συνεδρίες", desc: "Κρυπτογραφημένη σύνδεση και αυστηρός έλεγχος πρόσβασης στον χώρο σας." },
        { title: "Ειδοποιήσεις σε πραγματικό χρόνο", desc: "Email και SMS σε κάθε συναλλαγή στον λογαριασμό σας." },
        { title: "Έλεγχος κατά της απάτης", desc: "Ανάλυση των ευαίσθητων συναλλαγών πριν την επικύρωση." },
        { title: "Διαχωρισμένα κεφάλαια", desc: "Τα κεφάλαια των πελατών φυλάσσονται χωριστά από τα κεφάλαια της τράπεζας." },
      ],
    },
    faq: {
      title: "Συχνές ερωτήσεις",
      items: [
        { q: "Πώς ανοίγω λογαριασμό;", a: "Κάντε κλικ στο «Άνοιγμα λογαριασμού», συμπληρώστε τη φόρμα εγγραφής και επιλέξτε τη γλώσσα σας. Ο λογαριασμός σας δημιουργείται αμέσως με το IBAN σας." },
        { q: "Ποια έγγραφα χρειάζονται;", a: "Ένα έγκυρο έγγραφο ταυτότητας και τα στοιχεία επικοινωνίας σας. Δεν απαιτούνται φυσικά έγγραφα για το online άνοιγμα." },
        { q: "Πόσο διαρκεί μια μεταφορά;", a: "Οι μεταφορές SEPA εκτελούνται συνήθως μέσα σε μία εργάσιμη ημέρα. Οι διεθνείς εξαρτώνται από τη χώρα προορισμού." },
        { q: "Σε ποιες γλώσσες είναι διαθέσιμη η υπηρεσία;", a: "Η διεπαφή και οι ειδοποιήσεις είναι διαθέσιμες σε 16 γλώσσες." },
        { q: "Πώς επικοινωνώ με έναν σύμβουλο;", a: "Γράψτε στο contact@scap-ben.com ή χρησιμοποιήστε τον χώρο πελάτη: η ομάδα μας απαντά 7 ημέρες την εβδομάδα." },
      ],
    },
    cta: { title: "Έτοιμοι να ενταχθείτε στη SCAP BEN;", subtitle: "Ανοίξτε τον λογαριασμό σας σε λίγα λεπτά, από οπουδήποτε.", button: "Άνοιγμα λογαριασμού" },
    footer: { legal: "Νομικές πληροφορίες", privacy: "Πολιτική απορρήτου", terms: "Γενικοί όροι", rights: "Με επιφύλαξη παντός δικαιώματος." },
  },

  sl: {
    nav: { services: "Storitve", security: "Varnost", faq: "Pogosta vprašanja", login: "Prijava", openAccount: "Odprite račun" },
    hero: {
      badge: "Evropska spletna banka",
      title: "Vaša banka brez kompromisov.",
      subtitle: "Tekoči račun, plačilna kartica in mednarodni prenosi: upravljajte s svojim denarjem varno, kjerkoli ste.",
      ctaPrimary: "Odprite račun",
      ctaSecondary: "Prijava",
      trust1: "Ločena sredstva",
      trust2: "Evropski IBAN",
      trust3: "Večjezična podpora",
      photoAlt: "Svetovalec SCAP BEN pozdravlja dve stranki, ki pridita odpreti račun",
    },
    stats: [
      { value: "27", label: "Obslužane države" },
      { value: "16", label: "Razpoložljivi jeziki" },
      { value: "50.000+", label: "Aktivne stranke" },
      { value: "99,9 %", label: "Razpoložljivost" },
    ],
    services: {
      title: "Popolne storitve",
      subtitle: "Vse, kar ponuja sodobna banka, v preglednem in varnem prostoru.",
      cards: [
        { title: "Tekoči račun", desc: "Enostavno odpiranje, evropski IBAN in popolno upravljanje iz vašega prostora." },
        { title: "Plačilne kartice", desc: "Varné debitne kartice s takojšnjim spletnim nadzorom in blokado." },
        { title: "Prenosi", desc: "SEPA in mednarodni prenosi s sledenjem v realnem času." },
        { title: "Krediti", desc: "Spremljane zahtevke za posojila, pripisana po podpisu pogodbe." },
        { title: "PDF izpiski", desc: "Popolna zgodovina operacij, ki jo lahko kadar koli izvozite." },
        { title: "Podpora 7 dni v tednu", desc: "Večjezična ekipa dosegljiva po e-pošti in telefonu." },
      ],
    },
    product: {
      title: "Vaš denar, na prvi pogled",
      subtitle: "Pregledna nadzorna plošča: stanje, grafikoni in zgodovina z enim pogledom.",
      bullets: [
        { title: "Sledenje v realnem času", desc: "Vsaka operacija je takoj vidna s svojo referenco." },
        { title: "Prenosi v 3 klikih", desc: "IBAN, znesek, namen: vaši prenosi odidejo v nekaj sekundah." },
        { title: "Zgodovina za izvoz", desc: "Mesečni izpiski v PDF, pripravljeni za vaše računovodstvo." },
      ],
    },
    cardSection: {
      title: "Kartica SCAP BEN",
      subtitle: "Skromna, varna debitna kartica, sprejeta po vsem svetu.",
      bullets: [
        "Brezstična plačila in mednarodni dvigi",
        "Takojšnja blokada in odblokada iz vašega prostora",
        "Obvestila ob vsaki uporabi",
      ],
    },
    advisor: {
      title: "Človek ostaja v središču",
      text: "Za zaslonom stoji prava ekipa: naši svetovalci vas spremljajo pri odpiranju računa tako kot pri vsakodnevnih operacijah, v vašem jeziku.",
    },
    security: {
      title: "Varnost je naša prednost",
      subtitle: "Konkretna varstva, privzeto vklopljena.",
      items: [
        { title: "Zaščitene seje", desc: "Šifrirana povezava in strog nadzor dostopa do vašega prostora." },
        { title: "Opozorila v realnem času", desc: "E-pošta in SMS ob vsaki operaciji na vašem računu." },
        { title: "Nadzor proti goljufijam", desc: "Občutljive transakcije se analizirajo pred potrditvijo." },
        { title: "Ločena sredstva", desc: "Sredstva strank se hranijo ločeno od sredstev banke." },
      ],
    },
    faq: {
      title: "Pogosta vprašanja",
      items: [
        { q: "Kako odprem račun?", a: "Kliknite na »Odprite račun«, izpolnite prijavni obrazec in izberite svoj jezik. Vaš račun je ustvarjen takoj z vašim IBAN." },
        { q: "Kateri dokumenti so potrebni?", a: "Veljaven osebni dokument in vaši kontaktni podatki. Za spletno odpiranje niso potrebni nobeni fizični dokumenti." },
        { q: "Kako dolgo traja prenos?", a: "SEPA prenosi se običajno izvedejo v enem delovnem dnevu. Mednarodni prenosi so odvisni od ciljne države." },
        { q: "V katerih jezikih je storitev na voljo?", a: "Vmesnik in obvestila so na voljo v 16 jezikih." },
        { q: "Kako stopim v stik s svetovalcem?", a: "Pišite na contact@scap-ben.com ali uporabite strankino cono: naša ekipa odgovarja 7 dni v tednu." },
      ],
    },
    cta: { title: "Pripravljeni, da se pridružite SCAP BEN?", subtitle: "Odprite račun v nekaj minutah, od kjer koli.", button: "Odprite račun" },
    footer: { legal: "Pravne informacije", privacy: "Politika zasebnosti", terms: "Splošni pogoji", rights: "Vse pravice pridržane." },
  },

  lt: {
    nav: { services: "Paslaugos", security: "Saugumas", faq: "DUK", login: "Prisijungti", openAccount: "Atidaryti sąskaitą" },
    hero: {
      badge: "Europietiškas internetinis bankas",
      title: "Jūsų bankas be kompromisų.",
      subtitle: "Atsiskaitymo sąskaita, mokėjimo kortelė ir tarptautiniai pervedimai: tvarkykite savo pinigus saugiai, kur ir nebūtumėte.",
      ctaPrimary: "Atidaryti sąskaitą",
      ctaSecondary: "Prisijungti",
      trust1: "Atskirtos lėšos",
      trust2: "Europinis IBAN",
      trust3: "Daugiakalbė pagalba",
      photoAlt: "SCAP BEN konsultantas pasveikina du klientus, atėjusius atidaryti sąskaitą",
    },
    stats: [
      { value: "27", label: "Aptarnaujamos šalys" },
      { value: "16", label: "Prieinamos kalbos" },
      { value: "50 000+", label: "Aktyvūs klientai" },
      { value: "99,9 %", label: "Prieinamumas" },
    ],
    services: {
      title: "Išsamios paslaugos",
      subtitle: "Viskas, ką siūlo modernus bankas, aiškioje ir saugioje erdvėje.",
      cards: [
        { title: "Atsiskaitymo sąskaita", desc: "Paprastas atidarymas, europinis IBAN ir visas valdymas iš jūsų erdvės." },
        { title: "Mokėjimo kortelės", desc: "Saugios debeto kortelės su momentine internetine kontrole ir blokavimu." },
        { title: "Pervedimai", desc: "SEPA ir tarptautiniai pervedimai su stebėjimu realiuoju laiku." },
        { title: "Kreditai", desc: "Lydimos paskolų paraiškos, įskaitomos po sutarties pasirašymo." },
        { title: "PDF išrašai", desc: "Visa operacijų istorija, kurią galite eksportuoti bet kada." },
        { title: "Pagalba 7 dienas per savaitę", desc: "Daugiakalbė komanda pasiekiama el. paštu ir telefonu." },
      ],
    },
    product: {
      title: "Jūsų pinigai, matomi iš karto",
      subtitle: "Aiškus valdymo skydas: likutis, grafikai ir istorija vienu žvilgsniu.",
      bullets: [
        { title: "Stebėjimas realiuoju laiku", desc: "Kiekviena operacija matoma iškart su savo nuoroda." },
        { title: "Pervedimai per 3 paspaudimus", desc: "IBAN, suma, paskirtis: jūsų pervedimai iškeliauja per sekundes." },
        { title: "Eksportuojama istorija", desc: "Mėnesiniai PDF išrašai, paruošti jūsų apskaitai." },
      ],
    },
    cardSection: {
      title: "SCAP BEN kortelė",
      subtitle: "Paprasta, saugi debeto kortelė, priimama visame pasaulyje.",
      bullets: [
        "Bekontakčiai mokėjimai ir tarptautiniai išėmimai",
        "Momentinis blokavimas ir atrakinimas iš jūsų erdvės",
        "Pranešimai kiekvieno naudojimo metu",
      ],
    },
    advisor: {
      title: "Žmogus lieka centre",
      text: "Už ekrano stovi tikra komanda: mūsų konsultantai lydės jus atidarant sąskaitą taip pat ir kasdienėse operacijose, jūsų kalba.",
    },
    security: {
      title: "Saugumas – mūsų prioritetas",
      subtitle: "Konkretūs apsaugos sprendimai, įjungti pagal numatytuosius nustatymus.",
      items: [
        { title: "Apsaugoti seansai", desc: "Šifruotas ryšys ir griežta prieigos kontrolė į jūsų erdvę." },
        { title: "Įspėjimai realiuoju laiku", desc: "El. paštas ir SMS dėl kiekvienos operacijos jūsų sąskaitoje." },
        { title: "Apsauga nuo sukčiavimo", desc: "Jautrios operacijos analizuojamos prieš patvirtinimą." },
        { title: "Atskirtos lėšos", desc: "Klientų lėšos laikomos atskirai nuo banko lėšų." },
      ],
    },
    faq: {
      title: "Dažniausiai užduodami klausimai",
      items: [
        { q: "Kaip atidaryti sąskaitą?", a: "Spauskite „Atidaryti sąskaitą“, užpildykite registracijos formą ir pasirinkite savo kalbą. Jūsų sąskaita sukurama iškart su jūsų IBAN." },
        { q: "Kokius dokumentus reikia?", a: "Galiojantis tapatybės dokumentas ir jūsų kontaktiniai duomenys. Fiziniai dokumentai internetiniam atidarymui nereikalingi." },
        { q: "Kiek laiko trunka pervedimas?", a: "SEPA pervedimai paprastai atliekami per vieną darbo dieną. Tarptautiniai priklauso nuo gavėjos šalies." },
        { q: "Kuriomis kalbomis paslauga prieinama?", a: "Sąsaja ir pranešimai prieinami 16 kalbų." },
        { q: "Kaip susisiekti su konsultantu?", a: "Rašykite contact@scap-ben.com arba naudokite kliento erdvę: mūsų komanda atsako 7 dienas per savaitę." },
      ],
    },
    cta: { title: "Pasiruošę prisijungti prie SCAP BEN?", subtitle: "Atidarykite sąskaitą per kelias minutes, iš bet kur.", button: "Atidaryti sąskaitą" },
    footer: { legal: "Teisinė informacija", privacy: "Privatumo politika", terms: "Bendrosios sąlygos", rights: "Visos teisės saugomos." },
  },

  lv: {
    nav: { services: "Pakalpojumi", security: "Drošība", faq: "BUJ", login: "Pieteikties", openAccount: "Atvērt kontu" },
    hero: {
      badge: "Eiropas interneta banka",
      title: "Jūsu banka bez kompromisiem.",
      subtitle: "Norēķinu konts, maksājumu karte un starptautiski pārskaitījumi: pārvaldiet savu naudu droši, kur vien atrodaties.",
      ctaPrimary: "Atvērt kontu",
      ctaSecondary: "Pieteikties",
      trust1: "Atsevišķi līdzekļi",
      trust2: "Eiropas IBAN",
      trust3: "Daudzvalodu atbalsts",
      photoAlt: "SCAP BEN konsultants sagaida divus klientus, kas ieradušies atvērt kontu",
    },
    stats: [
      { value: "27", label: "Aptarnātās valstis" },
      { value: "16", label: "Pieejamās valodas" },
      { value: "50 000+", label: "Aktīvie klienti" },
      { value: "99,9 %", label: "Pieejamība" },
    ],
    services: {
      title: "Pilnvērtīgi pakalpojumi",
      subtitle: "Viss, ko piedāvā moderna banka, skaidrā un drošā telpā.",
      cards: [
        { title: "Norēķinu konts", desc: "Vienkārša atvēršana, Eiropas IBAN un pilna pārvaldība no savas telpas." },
        { title: "Maksājumu kartes", desc: "Drošas debetkartes ar tūlītēju tiešsaistes kontroli un bloķēšanu." },
        { title: "Pārskaitījumi", desc: "SEPA un starptautiski pārskaitījumi ar izsekošanu reāllaikā." },
        { title: "Kredīti", desc: "Pavadīti kredītpieteikumi, ieskaitīti pēc līguma parakstīšanas." },
        { title: "PDF izraksti", desc: "Pilna darījumu vēsture, ko var eksportēt jebkurā laikā." },
        { title: "Atbalsts 7 dienas nedēļā", desc: "Daudzvalodu komanda pieejama pa e-pastu un tālruni." },
      ],
    },
    product: {
      title: "Jūsu nauda acu priekšā",
      subtitle: "Skaidrs panelis: atlikums, diagrammas un vēsture vienā skatienā.",
      bullets: [
        { title: "Izsekošana reāllaikā", desc: "Katra darījuma redzama uzreici ar tā atsauci." },
        { title: "Pārskaitījumi 3 klikšķos", desc: "IBAN, summa, maksājuma mērķis: pārskaitījumi aiziet dažās sekundēs." },
        { title: "Eksportējama vēsture", desc: "Mēneša PDF izraksti, gatavi jūsu grāmatvedībai." },
      ],
    },
    cardSection: {
      title: "SCAP BEN karte",
      subtitle: "Vienkārša, droša debetkarte, ko pieņem visā pasaulē.",
      bullets: [
        "Bezkontakta maksājumi un starptautiskas izņemšanas",
        "Tūlītēja bloķēšana un atbloķēšana no savas telpas",
        "Paziņojumi pie katra lietojuma",
      ],
    },
    advisor: {
      title: "Cilvēks paliek centrā",
      text: "Aiz ekrāna ir īsta komanda: mūsu konsultanti pavadīs jūs konta atvēršanā, tāpat ikdienas darījumos, jūsu valodā.",
    },
    security: {
      title: "Drošība ir mūsu prioritāte",
      subtitle: "Konkrēti aizsardzības pasākumi, ieslēgti pēc noklusējuma.",
      items: [
        { title: "Aizsargātas sesijas", desc: "Šifrēts savienojums un stingra piekļuves kontrole jūsu telpai." },
        { title: "Brīdinājumi reāllaikā", desc: "E-pasts un SMS par katru darījumu jūsu kontā." },
        { title: "Krāpšanas novēršana", desc: "Jutīgi darījumi tiek analizēti pirms apstiprināšanas." },
        { title: "Atsevišķi līdzekļi", desc: "Klientu līdzekļi tiek glabāti atsevišķi no bankas līdzekļiem." },
      ],
    },
    faq: {
      title: "Biežāk uzdotie jautājumi",
      items: [
        { q: "Kā atvērt kontu?", a: "Noklikšķiniet uz „Atvērt kontu“, aizpildiet reģistrācijas veidlapu un izvēlieties savu valodu. Jūsu konts tiek izveidots nekavējoties ar jūsu IBAN." },
        { q: "Kādi dokumenti ir vajadzīgi?", a: "Derīgs identitātes dokuments un jūsu kontaktinformācija. Tiešsaistes atvēršanai fiziski dokumenti nav vajadzīgi." },
        { q: "Cik ilgs laiks nepieciešams pārskaitījumam?", a: "SEPA pārskaitījumus parasti izpilda vienas darba dienas laikā. Starptautiskie ir atkarīgi no adresāta valsts." },
        { q: "Kādās valodās pakalpojums pieejams?", a: "Saskarne un paziņojumi ir pieejami 16 valodās." },
        { q: "Kā sazināties ar konsultantu?", a: "Rakstiet uz contact@scap-ben.com vai izmantojiet klientu zonu: mūsu komanda atbild 7 dienas nedēļā." },
      ],
    },
    cta: { title: "Vai esat gatavs pievienoties SCAP BEN?", subtitle: "Atveriet kontu dažās minūtēs, no jebkuras vietas.", button: "Atvērt kontu" },
    footer: { legal: "Juridiskā informācija", privacy: "Konfidencialitātes politika", terms: "Vispārējie noteikumi", rights: "Visas tiesības aizsargātas." },
  },

  it: {
    nav: { services: "Servizi", security: "Sicurezza", faq: "FAQ", login: "Accedi", openAccount: "Apri un conto" },
    hero: {
      badge: "Banca online europea",
      title: "La tua banca, senza compromessi.",
      subtitle: "Conto corrente, carta di pagamento e bonifici internazionali: gestisci il tuo denaro in sicurezza, ovunque tu sia.",
      ctaPrimary: "Apri il tuo conto",
      ctaSecondary: "Accedi",
      trust1: "Fondi segregati",
      trust2: "IBAN europeo",
      trust3: "Assistenza multilingue",
      photoAlt: "Un consulente SCAP BEN accoglie due clienti venuti per aprire un conto",
    },
    stats: [
      { value: "27", label: "Paesi serviti" },
      { value: "16", label: "Lingue disponibili" },
      { value: "50.000+", label: "Clienti attivi" },
      { value: "99,9 %", label: "Disponibilità" },
    ],
    services: {
      title: "Servizi completi",
      subtitle: "Tutto il quotidiano di una banca moderna, in uno spazio chiaro e sicuro.",
      cards: [
        { title: "Conto corrente", desc: "Apertura semplice, IBAN europeo e gestione integrale dal tuo spazio." },
        { title: "Carte di pagamento", desc: "Carte di debito sicure, controllo e blocco istantanei online." },
        { title: "Bonifici", desc: "Bonifici SEPA e internazionali con monitoraggio in tempo reale." },
        { title: "Prestiti", desc: "Richieste di prestito accompagnate e accreditate dopo la firma del contratto." },
        { title: "Estratti conto PDF", desc: "Storico completo delle operazioni, esportabile in qualsiasi momento." },
        { title: "Assistenza 7 giorni su 7", desc: "Un team multilingue raggiungibile via email e telefono." },
      ],
    },
    product: {
      title: "Il tuo denaro, sotto i tuoi occhi",
      subtitle: "Una dashboard chiara: saldo, grafici e storico a colpo d'occhio.",
      bullets: [
        { title: "Monitoraggio in tempo reale", desc: "Ogni operazione è visibile immediatamente con il suo riferimento." },
        { title: "Bonifici in 3 clic", desc: "IBAN, importo, causale: i tuoi bonifici partono in pochi secondi." },
        { title: "Storico esportabile", desc: "Estratti mensili in PDF, pronti per la tua contabilità." },
      ],
    },
    cardSection: {
      title: "La carta SCAP BEN",
      subtitle: "Una carta di debito sobria e sicura, accettata in tutto il mondo.",
      bullets: [
        "Pagamenti contactless e prelievi internazionali",
        "Blocco e sblocco istantanei dal tuo spazio",
        "Notifiche a ogni utilizzo",
      ],
    },
    advisor: {
      title: "La persona resta al centro",
      text: "Dietro lo schermo c'è un vero team: i nostri consulenti ti accompagnano all'apertura del conto così come nelle operazioni quotidiane, nella tua lingua.",
    },
    security: {
      title: "La sicurezza, la nostra priorità",
      subtitle: "Protezioni concrete, attive per impostazione predefinita.",
      items: [
        { title: "Sessioni protette", desc: "Connessione crittografata e controllo degli accessi rigoroso al tuo spazio." },
        { title: "Avvisi in tempo reale", desc: "Email e SMS a ogni operazione sul tuo conto." },
        { title: "Verifica antifrode", desc: "Analisi delle operazioni sensibili prima della validazione." },
        { title: "Fondi segregati", desc: "I fondi dei clienti sono conservati separatamente dai fondi della banca." },
      ],
    },
    faq: {
      title: "Domande frequenti",
      items: [
        { q: "Come si apre un conto?", a: "Clicca su «Apri un conto», compila il modulo di registrazione e scegli la tua lingua. Il tuo conto viene creato immediatamente con il tuo IBAN." },
        { q: "Quali documenti servono?", a: "Un documento d'identità valido e i tuoi recapiti. Nessun documento fisico è richiesto per l'apertura online." },
        { q: "Quanto tempo richiede un bonifico?", a: "I bonifici SEPA vengono generalmente eseguiti entro un giorno lavorativo. Quelli internazionali dipendono dal paese di destinazione." },
        { q: "In quali lingue è disponibile il servizio?", a: "L'interfaccia e le notifiche sono disponibili in 16 lingue." },
        { q: "Come contattare un consulente?", a: "Scrivi a contact@scap-ben.com o usa la tua area clienti: il nostro team risponde 7 giorni su 7." },
      ],
    },
    cta: { title: "Pronto a unirti a SCAP BEN?", subtitle: "Apri il tuo conto in pochi minuti, da qualsiasi luogo.", button: "Apri il tuo conto" },
    footer: { legal: "Note legali", privacy: "Informativa sulla privacy", terms: "Termini e condizioni", rights: "Tutti i diritti riservati." },
  },

  cs: {
    nav: { services: "Služby", security: "Zabezpečení", faq: "Časté dotazy", login: "Přihlásit se", openAccount: "Otevřít účet" },
    hero: {
      badge: "Evropská internetová banka",
      title: "Vaše banka bez kompromisů.",
      subtitle: "Běžný účet, platební karta a mezinárodní převody: spravujte své peníze bezpečně, ať jste kdekoli.",
      ctaPrimary: "Otevřít účet",
      ctaSecondary: "Přihlásit se",
      trust1: "Oddělené prostředky",
      trust2: "Evropský IBAN",
      trust3: "Vícejazyčná podpora",
      photoAlt: "Poradce SCAP BEN vítá dva klienty, kteří přicházejí otevřít účet",
    },
    stats: [
      { value: "27", label: "Obsluhované země" },
      { value: "16", label: "Dostupné jazyky" },
      { value: "50 000+", label: "Aktivní klienti" },
      { value: "99,9 %", label: "Dostupnost" },
    ],
    services: {
      title: "Kompletní služby",
      subtitle: "Vše, co nabízí moderní banka, v přehledném a bezpečném prostoru.",
      cards: [
        { title: "Běžný účet", desc: "Jednoduché založení, evropský IBAN a kompletní správa z vašeho prostoru." },
        { title: "Platební karty", desc: "Bezpečné debetní karty s okamžitým online ovládáním a blokováním." },
        { title: "Převody", desc: "Převody SEPA a mezinárodní se sledováním v reálném čase." },
        { title: "Úvěry", desc: "Doprovázené žádosti o úvěr, připsané po podpisu smlouvy." },
        { title: "Výpisy PDF", desc: "Úplná historie operací, kterou kdykoli vyexportujete." },
        { title: "Podpora 7 dní v týdnu", desc: "Vícejazyčný tým dostupný e-mailem a telefonem." },
      ],
    },
    product: {
      title: "Vaše peníze na první pohled",
      subtitle: "Přehledný dashboard: zůstatek, grafy a historie na jeden pohled.",
      bullets: [
        { title: "Sledování v reálném čase", desc: "Každá operace je okamžitě viditelná se svou referencí." },
        { title: "Převody na 3 kliknutí", desc: "IBAN, částka, poznámka: převody odcházejí během pár sekund." },
        { title: "Exportovatelná historie", desc: "Měsíční výpisy v PDF, připravené pro vaše účetnictví." },
      ],
    },
    cardSection: {
      title: "Karta SCAP BEN",
      subtitle: "Střídmá, bezpečná debetní karta přijímaná po celém světě.",
      bullets: [
        "Bezkontaktní platby a mezinárodní výběry",
        "Okamžité zablokování a odblokování z vašeho prostoru",
        "Upozornění při každém použití",
      ],
    },
    advisor: {
      title: "Člověk zůstává ve středu",
      text: "Za obrazovkou stojí skutečný tým: naši poradci vás doprovázejí při zakládání účtu i při každodenních operacích, ve vašem jazyce.",
    },
    security: {
      title: "Zabezpečení je naší prioritou",
      subtitle: "Konkrétní ochrany, aktivní ve výchozím nastavení.",
      items: [
        { title: "Chráněná sezení", desc: "Šifrované připojení a přísná kontrola přístupu do vašeho prostoru." },
        { title: "Upozornění v reálném čase", desc: "E-mail a SMS při každé operaci na vašem účtu." },
        { title: "Kontrola proti podvodům", desc: "Citlivé operace se před schválením analyzují." },
        { title: "Oddělené prostředky", desc: "Prostředky klientů jsou uloženy odděleně od prostředků banky." },
      ],
    },
    faq: {
      title: "Časté dotazy",
      items: [
        { q: "Jak si otevřu účet?", a: "Klikněte na „Otevřít účet“, vyplňte registrační formulář a zvolte si jazyk. Váš účet je vytvořen okamžitě s vaším IBAN." },
        { q: "Jaké dokumenty jsou potřeba?", a: "Platný doklad totožnosti a vaše kontaktní údaje. Pro online založení nejsou potřeba žádné fyzické dokumenty." },
        { q: "Jak dlouho trvá převod?", a: "Převody SEPA se obvykle provádějí do jednoho pracovního dne. Mezinárodní převody závisí na zemi určení." },
        { q: "Ve kterých jazycích je služba dostupná?", a: "Rozhraní a oznámení jsou dostupná ve 16 jazycích." },
        { q: "Jak kontaktovat poradce?", a: "Pište na contact@scap-ben.com nebo využijte klientskou zónu: náš tým odpovídá 7 dní v týdnu." },
      ],
    },
    cta: { title: "Připraveni se připojit k SCAP BEN?", subtitle: "Otevřete si účet za pár minut, odkudkoli.", button: "Otevřít účet" },
    footer: { legal: "Právní informace", privacy: "Zásady ochrany osobních údajů", terms: "Všeobecné podmínky", rights: "Všechna práva vyhrazena." },
  },
};

export function getHomeContent(locale) {
  return HOME_CONTENT[locale] || HOME_CONTENT.fr;
}
